### ISSUE TITLE
"Error in function (classes,fdef,mtable)" when combining coverage data and peak data in the same plotTracks function

### ISSUE THREAD

**Issue by alicekcassel** [RockefellerUniversity/RU_VisualizingGenomicsData#1]
I'm getting an error when I try to combine the coverage data from the bw files and the peak data from the bed files into one plotTracks function. My other plotTracks before this one work just fine and look like the ones in the exercises. 
The error is:
**`> plotTracks(c(mycmelpeaksDT,mycmelbwDT,mycchr12peaksDT,mycchr12bw),chromosome="chr2",from=135522235,to=135531066,ylim=c(0,40),cex=2)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'displayPars<-' for signature '"GRanges", "list"'`**

Rest of the code before error:
`library(rtracklayer)
myc_melPeaks <- import.bed("myc_mel.bed")
library(IRanges)
mycmelpeaksDT <- DataTrack(myc_melPeaks,chromosome="chr2",from=135522235,to=135531066,name="Mel_peaks",type="b")
myc_chr12 <- import.bed("myc_ch12.bed")
mycchr12peaksDT <- DataTrack(myc_chr12,chromosome="chr2",from=135522235,to=135531066,name="chr12_peaks",type="b")
plotTracks(c(mycmelpeaksDT,mycchr12peaksDT),chromosome="chr2",from=135522235,to=135531066,type="b",cex=2)
mycmelbw <- import.bw("myc_mel.bw",as="GRanges")
mycmelbwDT <- DataTrack(mycmelbw,chromosome="chr2",from=135522235,to=135531066,name="Mel_peaks",type="hist")
mycchr12bw <- import.bw("myc_ch12.bw",as="GRanges")
mycchr12bwDT <- DataTrack(mycchr12bw,chromosome="chr2",from=135522235,to=135531066,name="Chr12_peaks",type="hist")
plotTracks(c(mycmelbwDT,mycchr12bwDT),chromosome="chr2",from=135522235,to=135531066,type="hist",ylim=c(0,40))
plotTracks(c(mycmelpeaksDT,mycmelbwDT,mycchr12peaksDT,mycchr12bw),chromosome="chr2",from=135522235,to=135531066,ylim=c(0,40),cex=2)`

(sorry, I'm not sure why the code looks like this when I insert it here)

Thanks!

**Comment by ThomasCarroll** [comment]
hey Alice,

In
` plotTracks(c(mycmelpeaksDT,mycmelbwDT,mycchr12peaksDT,mycchr12bw)`

Should that be mycchr12bwDT?

thanks,
tom

**Comment by alicekcassel** [comment]
Yes, thank you! Missed that little problem
